"""0011 Update default factory for user's registered_at

Revision ID: 0fea78cbcf31
Revises: 28061f8d7e03
Create Date: 2021-12-30 21:30:46.072608

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "0fea78cbcf31"
down_revision = "28061f8d7e03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
