"""0004 Add relation from Access Token to Refresh Token

Revision ID: 1d287d3c6462
Revises: c91a6571c007
Create Date: 2021-12-26 22:05:04.818901

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "1d287d3c6462"
down_revision = "c91a6571c007"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstoken",
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(
        op.f("ix_accesstoken_refresh_token"),
        "accesstoken",
        ["refresh_token"],
        unique=False,
    )
    op.create_foreign_key(
        None, "accesstoken", "refreshtoken", ["refresh_token"], ["token"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "accesstoken", type_="foreignkey")
    op.drop_index(op.f("ix_accesstoken_refresh_token"), table_name="accesstoken")
    op.drop_column("accesstoken", "refresh_token")
    # ### end Alembic commands ###
