"""0013 Update source_refresh_token relation

Revision ID: 2493c3efa2bc
Revises: 3181b9756c0f
Create Date: 2021-12-31 17:04:12.886744

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "2493c3efa2bc"
down_revision = "3181b9756c0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstoken",
        sa.Column(
            "source_refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.drop_index("ix_accesstoken_refresh_token", table_name="accesstoken")
    op.create_index(
        op.f("ix_accesstoken_source_refresh_token"),
        "accesstoken",
        ["source_refresh_token"],
        unique=False,
    )
    op.drop_constraint(
        "accesstoken_refresh_token_fkey", "accesstoken", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "accesstoken", "refreshtoken", ["source_refresh_token"], ["token"]
    )
    op.drop_column("accesstoken", "refresh_token")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstoken",
        sa.Column("refresh_token", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "accesstoken", type_="foreignkey")
    op.create_foreign_key(
        "accesstoken_refresh_token_fkey",
        "accesstoken",
        "refreshtoken",
        ["refresh_token"],
        ["token"],
    )
    op.drop_index(op.f("ix_accesstoken_source_refresh_token"), table_name="accesstoken")
    op.create_index(
        "ix_accesstoken_refresh_token", "accesstoken", ["refresh_token"], unique=False
    )
    op.drop_column("accesstoken", "source_refresh_token")
    # ### end Alembic commands ###
