"""0010 Make username nullable

Revision ID: 28061f8d7e03
Revises: 575d6d6b784a
Create Date: 2021-12-30 21:25:14.744630

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "28061f8d7e03"
down_revision = "575d6d6b784a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "username", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "username", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    # ### end Alembic commands ###
