"""0012 Make email required

Revision ID: 3181b9756c0f
Revises: 0fea78cbcf31
Create Date: 2021-12-30 21:36:10.720302

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "3181b9756c0f"
down_revision = "0fea78cbcf31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", existing_type=sa.VARCHAR(length=64), nullable=True)
    # ### end Alembic commands ###
