"""Initial migration

Revision ID: 3554b9a4737c
Revises: 91010c835990
Create Date: 2021-12-18 23:00:22.249187

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "3554b9a4737c"
down_revision = "91010c835990"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstoken",
        sa.Column("access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_index("ix_accesstoken_token", table_name="accesstoken")
    op.create_index(
        op.f("ix_accesstoken_access_token"),
        "accesstoken",
        ["access_token"],
        unique=False,
    )
    op.drop_column("accesstoken", "token")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstoken",
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_accesstoken_access_token"), table_name="accesstoken")
    op.create_index("ix_accesstoken_token", "accesstoken", ["token"], unique=False)
    op.drop_column("accesstoken", "access_token")
    # ### end Alembic commands ###
