"""0017 Make is_superuser field not nullable

Revision ID: 3898bb8b6c04
Revises: 63889042b1e1
Create Date: 2022-01-21 20:34:15.154791

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "3898bb8b6c04"
down_revision = "63889042b1e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
