"""0014 Refactor models

Revision ID: 3a89b996ecbe
Revises: 2493c3efa2bc
Create Date: 2021-12-31 17:28:27.190189

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "3a89b996ecbe"
down_revision = "2493c3efa2bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refreshtoken",
        sa.Column(
            "related_access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.drop_index("ix_refreshtoken_access_token", table_name="refreshtoken")
    op.create_index(
        op.f("ix_refreshtoken_related_access_token"),
        "refreshtoken",
        ["related_access_token"],
        unique=False,
    )
    op.drop_constraint(
        "refreshtoken_access_token_fkey", "refreshtoken", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "refreshtoken", "accesstoken", ["related_access_token"], ["access_token"]
    )
    op.drop_column("refreshtoken", "access_token")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refreshtoken",
        sa.Column("access_token", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "refreshtoken", type_="foreignkey")
    op.create_foreign_key(
        "refreshtoken_access_token_fkey",
        "refreshtoken",
        "accesstoken",
        ["access_token"],
        ["access_token"],
    )
    op.drop_index(
        op.f("ix_refreshtoken_related_access_token"), table_name="refreshtoken"
    )
    op.create_index(
        "ix_refreshtoken_access_token", "refreshtoken", ["access_token"], unique=False
    )
    op.drop_column("refreshtoken", "related_access_token")
    # ### end Alembic commands ###
