"""0016 add is_superuser flag to user model

Revision ID: 63889042b1e1
Revises: eca6a56b7590
Create Date: 2022-01-21 20:09:44.149690

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "63889042b1e1"
down_revision = "eca6a56b7590"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_superuser", sa.Boolean(), nullable=True))
    op.create_index(
        op.f("ix_user_is_superuser"), "user", ["is_superuser"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_is_superuser"), table_name="user")
    op.drop_column("user", "is_superuser")
    # ### end Alembic commands ###
