"""Initial migration

Revision ID: 91010c835990
Revises: c625a9f0f763
Create Date: 2021-12-18 22:54:40.320351

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "91010c835990"
down_revision = "c625a9f0f763"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstoken",
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
    )
    op.drop_index("ix_accesstoken_user", table_name="accesstoken")
    op.create_index(
        op.f("ix_accesstoken_user_id"), "accesstoken", ["user_id"], unique=False
    )
    op.drop_constraint("accesstoken_user_fkey", "accesstoken", type_="foreignkey")
    op.create_foreign_key(None, "accesstoken", "user", ["user_id"], ["id"])
    op.drop_column("accesstoken", "user")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstoken",
        sa.Column("user", postgresql.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "accesstoken", type_="foreignkey")
    op.create_foreign_key(
        "accesstoken_user_fkey", "accesstoken", "user", ["user"], ["id"]
    )
    op.drop_index(op.f("ix_accesstoken_user_id"), table_name="accesstoken")
    op.create_index("ix_accesstoken_user", "accesstoken", ["user"], unique=False)
    op.drop_column("accesstoken", "user_id")
    # ### end Alembic commands ###
