"""0006 Update relations to Application model

Revision ID: ace5057a7b29
Revises: ebac7d806f63
Create Date: 2021-12-26 22:44:32.611807

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "ace5057a7b29"
down_revision = "ebac7d806f63"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstoken",
        sa.Column("application_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_index("ix_accesstoken_application", table_name="accesstoken")
    op.create_index(
        op.f("ix_accesstoken_application_id"),
        "accesstoken",
        ["application_id"],
        unique=False,
    )
    op.drop_constraint(
        "accesstoken_application_fkey", "accesstoken", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "accesstoken", "application", ["application_id"], ["client_id"]
    )
    op.drop_column("accesstoken", "application")
    op.add_column(
        "refreshtoken",
        sa.Column("application_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_index("ix_refreshtoken_application", table_name="refreshtoken")
    op.create_index(
        op.f("ix_refreshtoken_application_id"),
        "refreshtoken",
        ["application_id"],
        unique=False,
    )
    op.drop_constraint(
        "refreshtoken_application_fkey", "refreshtoken", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "refreshtoken", "application", ["application_id"], ["client_id"]
    )
    op.drop_column("refreshtoken", "application")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refreshtoken",
        sa.Column("application", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "refreshtoken", type_="foreignkey")
    op.create_foreign_key(
        "refreshtoken_application_fkey",
        "refreshtoken",
        "application",
        ["application"],
        ["client_id"],
    )
    op.drop_index(op.f("ix_refreshtoken_application_id"), table_name="refreshtoken")
    op.create_index(
        "ix_refreshtoken_application", "refreshtoken", ["application"], unique=False
    )
    op.drop_column("refreshtoken", "application_id")
    op.add_column(
        "accesstoken",
        sa.Column("application", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "accesstoken", type_="foreignkey")
    op.create_foreign_key(
        "accesstoken_application_fkey",
        "accesstoken",
        "application",
        ["application"],
        ["client_id"],
    )
    op.drop_index(op.f("ix_accesstoken_application_id"), table_name="accesstoken")
    op.create_index(
        "ix_accesstoken_application", "accesstoken", ["application"], unique=False
    )
    op.drop_column("accesstoken", "application_id")
    # ### end Alembic commands ###
