"""0005 Create Application model

Revision ID: b9b2d8e8ca3d
Revises: 1d287d3c6462
Create Date: 2021-12-26 22:14:39.509192

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "b9b2d8e8ca3d"
down_revision = "1d287d3c6462"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application",
        sa.Column(
            "client_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "client_secret",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("redirect_uris", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_index(
        op.f("ix_application_client_id"), "application", ["client_id"], unique=True
    )
    op.create_index(
        op.f("ix_application_client_secret"),
        "application",
        ["client_secret"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_created_at"), "application", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_application_redirect_uris"),
        "application",
        ["redirect_uris"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_updated_at"), "application", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_application_user_id"), "application", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_application_user_id"), table_name="application")
    op.drop_index(op.f("ix_application_updated_at"), table_name="application")
    op.drop_index(op.f("ix_application_redirect_uris"), table_name="application")
    op.drop_index(op.f("ix_application_created_at"), table_name="application")
    op.drop_index(op.f("ix_application_client_secret"), table_name="application")
    op.drop_index(op.f("ix_application_client_id"), table_name="application")
    op.drop_table("application")
    # ### end Alembic commands ###
