"""Initial migration

Revision ID: c625a9f0f763
Revises: 8893e302a510
Create Date: 2021-12-18 22:50:59.220999

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "c625a9f0f763"
down_revision = "8893e302a510"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accesstoken",
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("user", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_accesstoken_created_at"), "accesstoken", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_accesstoken_expires_at"), "accesstoken", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_accesstoken_id"), "accesstoken", ["id"], unique=False)
    op.create_index(
        op.f("ix_accesstoken_is_active"), "accesstoken", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_accesstoken_scope"), "accesstoken", ["scope"], unique=False
    )
    op.create_index(
        op.f("ix_accesstoken_token"), "accesstoken", ["token"], unique=False
    )
    op.create_index(
        op.f("ix_accesstoken_token_type"), "accesstoken", ["token_type"], unique=False
    )
    op.create_index(op.f("ix_accesstoken_user"), "accesstoken", ["user"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_accesstoken_user"), table_name="accesstoken")
    op.drop_index(op.f("ix_accesstoken_token_type"), table_name="accesstoken")
    op.drop_index(op.f("ix_accesstoken_token"), table_name="accesstoken")
    op.drop_index(op.f("ix_accesstoken_scope"), table_name="accesstoken")
    op.drop_index(op.f("ix_accesstoken_is_active"), table_name="accesstoken")
    op.drop_index(op.f("ix_accesstoken_id"), table_name="accesstoken")
    op.drop_index(op.f("ix_accesstoken_expires_at"), table_name="accesstoken")
    op.drop_index(op.f("ix_accesstoken_created_at"), table_name="accesstoken")
    op.drop_table("accesstoken")
    # ### end Alembic commands ###
