"""0003 Create Refresh Token model

Revision ID: c91a6571c007
Revises: a899a4a9c223
Create Date: 2021-12-26 22:04:41.875271

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "c91a6571c007"
down_revision = "a899a4a9c223"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refreshtoken",
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["access_token"],
            ["accesstoken.access_token"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index(
        op.f("ix_refreshtoken_access_token"),
        "refreshtoken",
        ["access_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refreshtoken_created_at"), "refreshtoken", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_refreshtoken_revoked_at"), "refreshtoken", ["revoked_at"], unique=False
    )
    op.create_index(
        op.f("ix_refreshtoken_token"), "refreshtoken", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_refreshtoken_updated_at"), "refreshtoken", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_refreshtoken_user_id"), "refreshtoken", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refreshtoken_user_id"), table_name="refreshtoken")
    op.drop_index(op.f("ix_refreshtoken_updated_at"), table_name="refreshtoken")
    op.drop_index(op.f("ix_refreshtoken_token"), table_name="refreshtoken")
    op.drop_index(op.f("ix_refreshtoken_revoked_at"), table_name="refreshtoken")
    op.drop_index(op.f("ix_refreshtoken_created_at"), table_name="refreshtoken")
    op.drop_index(op.f("ix_refreshtoken_access_token"), table_name="refreshtoken")
    op.drop_table("refreshtoken")
    # ### end Alembic commands ###
