"""0007 Update datetime fields

Revision ID: ea6cf3ae3ecf
Revises: ace5057a7b29
Create Date: 2021-12-27 18:55:32.964071

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ea6cf3ae3ecf"
down_revision = "ace5057a7b29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accesstoken", "expires_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "accesstoken", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_index("ix_accesstoken_created_at", table_name="accesstoken")
    op.drop_index("ix_accesstoken_expires_at", table_name="accesstoken")
    op.alter_column(
        "application", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_index("ix_application_created_at", table_name="application")
    op.drop_index("ix_application_updated_at", table_name="application")
    op.drop_index("ix_refreshtoken_created_at", table_name="refreshtoken")
    op.drop_index("ix_refreshtoken_revoked_at", table_name="refreshtoken")
    op.drop_index("ix_refreshtoken_updated_at", table_name="refreshtoken")
    op.add_column(
        "user", sa.Column("registered_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "user", sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_index("ix_user_is_active", table_name="user")
    op.drop_column("user", "is_active")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.create_index("ix_user_is_active", "user", ["is_active"], unique=False)
    op.drop_column("user", "deactivated_at")
    op.drop_column("user", "registered_at")
    op.create_index(
        "ix_refreshtoken_updated_at", "refreshtoken", ["updated_at"], unique=False
    )
    op.create_index(
        "ix_refreshtoken_revoked_at", "refreshtoken", ["revoked_at"], unique=False
    )
    op.create_index(
        "ix_refreshtoken_created_at", "refreshtoken", ["created_at"], unique=False
    )
    op.create_index(
        "ix_application_updated_at", "application", ["updated_at"], unique=False
    )
    op.create_index(
        "ix_application_created_at", "application", ["created_at"], unique=False
    )
    op.alter_column(
        "application",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.create_index(
        "ix_accesstoken_expires_at", "accesstoken", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_accesstoken_created_at", "accesstoken", ["created_at"], unique=False
    )
    op.alter_column(
        "accesstoken",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "accesstoken",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # ### end Alembic commands ###
