"""0006 Add relations to Application model

Revision ID: ebac7d806f63
Revises: b9b2d8e8ca3d
Create Date: 2021-12-26 22:41:50.240931

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "ebac7d806f63"
down_revision = "b9b2d8e8ca3d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstoken",
        sa.Column("application", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(
        op.f("ix_accesstoken_application"), "accesstoken", ["application"], unique=False
    )
    op.create_foreign_key(
        None, "accesstoken", "application", ["application"], ["client_id"]
    )
    op.add_column(
        "refreshtoken",
        sa.Column("application", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(
        op.f("ix_refreshtoken_application"),
        "refreshtoken",
        ["application"],
        unique=False,
    )
    op.create_foreign_key(
        None, "refreshtoken", "application", ["application"], ["client_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "refreshtoken", type_="foreignkey")
    op.drop_index(op.f("ix_refreshtoken_application"), table_name="refreshtoken")
    op.drop_column("refreshtoken", "application")
    op.drop_constraint(None, "accesstoken", type_="foreignkey")
    op.drop_index(op.f("ix_accesstoken_application"), table_name="accesstoken")
    op.drop_column("accesstoken", "application")
    # ### end Alembic commands ###
