"""0015 Add verified_at field to User model

Revision ID: eca6a56b7590
Revises: 55e271aa67b2
Create Date: 2022-01-02 14:29:24.715789

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "eca6a56b7590"
down_revision = "55e271aa67b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "verified_at")
    # ### end Alembic commands ###
